// React/hw5-todo-react/src/components/Identity/Register.tsx
import React, { useEffect } from 'react';

export default function Register() {

    return (
        <div className="text-center">
            <h1>Create a new account</h1>

            <div className="row justify-content-center">
                <div className="col-md-4">
                    <form method="post" >
                        <hr />

                        <div className="text-danger validation-summary-valid" data-valmsg-summary="true">
                            <ul>
                                <li >

                                </li>
                            </ul>
                        </div>

                        <div className="form-group">
                            <label htmlFor="email">Email</label>
                            <input className="form-control" type="email" id="email" name="email"/>
                        </div>

                        <div className="form-group">
                            <label htmlFor="password">Password</label>
                            <input className="form-control" type="password" id="password" name="password"/>
                        </div>

                        <div className="form-group">
                            <label htmlFor="conf_password">Confirm password</label>
                            <input className="form-control" type="password" id="conf_password" name="conf_password" />
                        </div>

                        <button type="submit" className="btn btn-primary">Register</button>

                        <p className="mt-3">
                            <a route-href="route: account-login">Already have an account? Login</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    )
}

// Homeproject/vue/vue-artnetwork/src/views/account/Register.vue
<template>
  <div class="text-center">
    <h1>Create a new account</h1>

    <div class="row justify-content-center">
      <div class="col-md-4">
        <form>
          <hr />
          <div class="text-danger validation-summary-valid" data-valmsg-summary="true">
            <ul>
              <li v-for="(error, index) in errors" :key="index">{{error}}</li>
            </ul>
          </div>
          <div class="form-group">
            <label for="Input_Username">Username</label>
            <input class="form-control" type="text" v-model="registerModel.username" />
            <span class="text-danger field-validation-valid" data-valmsg-for="Input.Username" data-valmsg-replace="true"></span>
          </div>
          <div class="form-group">
            <label for="Input_Email">Email</label>
            <input class="form-control" type="email" v-model="registerModel.email" />
            <span class="text-danger field-validation-valid" data-valmsg-for="Input.Email" data-valmsg-replace="true"></span>
          </div>
          <div class="form-group">
            <label for="Input_Password">Password</label>
            <input class="form-control" type="password" v-model="registerModel.password" />
            <span class="text-danger field-validation-valid" data-valmsg-for="Input.Password" data-valmsg-replace="true"></span>
          </div>
          <div class="form-group">
            <label for="Input_ConfirmPassword">Confirm password</label>
            <input class="form-control" type="password" v-model="passwordConfirmation" />
            <span class="text-danger field-validation-valid" data-valmsg-for="Input.ConfirmPassword" data-valmsg-replace="true"></span>
          </div>
          <button type="submit" class="btn btn-primary" @click="onSubmit">Register</button>
          <p class="mt-3">
            <router-link to="login">Already have an account? Login</router-link>
          </p>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { IRegisterDTO } from "@/types/Identity/IRegisterDTO";
import { ResponseDTO } from "@/types/Response/ResponseDTO";
import store from "../../store";
import router from "../../router";

@Component
export default class AccountRegister extends Vue {
  private passwordConfirmation = "";

  private registerModel: IRegisterDTO = {
    username: "",
    email: "",
    password: ""
  };

  private errors: string[] = [];

  onSubmit(e: Event): void {
    this.errors = [];

    if (
      this.registerModel.username.length > 0 &&
      this.registerModel.email.length > 0 &&
      this.registerModel.password.length > 0 &&
      this.registerModel.password === this.passwordConfirmation
    ) {
      store
        .dispatch("registerUser", this.registerModel)
        .then((response: ResponseDTO) => {
          if (response.errors) {
            this.errors = response.errors;
          } else {
            router.push("/account/login");
          }
        });
    } else {
      this.errors.push("Passwords do not match!");
    }

    e.preventDefault();
  }
}
</script>
