// Homeproject/vue/vue-artnetwork/src/views/account/Login.vue
<template>
  <div class="text-center">
    <h1>Log in</h1>
    <div class="row justify-content-center">
      <div class="col-md-4">
        <section>
          <form>
            <hr />
            <div class="text-danger validation-summary-valid" data-valmsg-summary="true">
              <ul>
                <li v-for="(error, index) in errors" :key="index">{{error}}</li>
              </ul>
            </div>
            <div class="form-group">
              <label for="Input_Email">Email</label>
              <input class="form-control" type="email" v-model="loginModel.email" />
              <span class="text-danger field-validation-valid"></span>
            </div>
            <div class="form-group">
              <label for="Input_Password">Password</label>
              <input class="form-control" type="password" v-model="loginModel.password" />
              <span class="text-danger field-validation-valid" data-valmsg-for="Input.Password" data-valmsg-replace="true"></span>
            </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary" @click="onSubmit" v-on:keyup.enter="onSubmit">Log in</button>
            </div>
            <div class="form-group">
              <p>
                <router-link to="register">Do not have an account yet? Register</router-link>
              </p>
            </div>
          </form>
        </section>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { ILoginDTO } from "@/types/Identity/ILoginDTO";
import store from "../../store";
import router from "../../router";
import { JwtResponseDTO } from "@/types/Response/JwtResponseDTO";

@Component
export default class AccountLogin extends Vue {
  private loginModel: ILoginDTO = {
    email: "",
    password: ""
  };

  private errors: string[] = [];

  onSubmit(e: Event): void {
    this.errors = [];

    if (
      this.loginModel.email.length > 0 &&
      this.loginModel.password.length > 0
    ) {
      store
        .dispatch("loginUser", this.loginModel)
        .then((response: JwtResponseDTO) => {
          if (response.errors) {
            this.errors = response.errors;
            console.log(response.errors);
          } else {
            router.push("/");
          }
        });
    }
    e.preventDefault();
  }
}
</script>

// React/hw5-todo-react/src/components/Identity/Login.tsx
import React from 'react';

import { useDispatch } from 'react-redux'

import { login } from 'redux/account/actions';
import { Link } from 'react-router-dom';

export default function Login() {

    const dispatch = useDispatch()

    const onLogin = () => {
        dispatch(login({ email: "aleksi@ttu.ee", password: "Admin_123" }))
    }

    return (
        <div className="text-center">
            <h1>Log in</h1>
            <div className="row justify-content-center">
                <div className="col-md-4">
                    <section>
                        <hr />
                        <div className="text-danger validation-summary-valid" data-valmsg-summary="true">
                            <ul>
                                <li>
                                </li>
                            </ul>
                        </div>

                        <div className="form-group">
                            <label htmlFor="email">Email</label>
                            <input className="form-control" type="email" id="email" name="email" />
                        </div>

                        <div className="form-group">
                            <label htmlFor="password">Password</label>
                            <input className="form-control" type="password" id="password" name="password" />
                        </div>

                        <div className="form-group">
                            <button type="submit" className="btn btn-primary" onClick={onLogin}>
                                Log in
                            </button>
                        </div>

                        <div className="form-group">
                            <p>
                                <Link replace to="/account/register">Do not have an account yet? Register</Link>
                            </p>
                        </div>
                    </section>
                </div>
            </div>
        </div >
    )
}
